# Generated by Django 4.2.2 on 2023-06-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
