# Generated by Django 4.2.2 on 2023-06-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_candidate_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='website',
        ),
    ]
