# Generated by Django 4.2.2 on 2023-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_candidate_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='client_id',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
