# Generated by Django 4.2.2 on 2023-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_user_id_candidate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(max_length=250),
        ),
    ]
