# Generated by Django 4.2.2 on 2023-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_candidate_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
