# Generated by Django 4.2.2 on 2023-06-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_jobdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='compantcontact',
            new_name='companycontact',
        ),
    ]
