# Generated by Django 4.2.2 on 2023-06-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_compantcontact_jobdetails_companycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
