# Generated by Django 4.2.2 on 2023-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_jobdetails_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='companywebsite',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
