# Generated by Django 4.2.2 on 2023-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
    ]
