# Generated by Django 4.2.2 on 2023-07-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_candidate_max_salary_candidate_min_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='experience',
            new_name='experiences',
        ),
        migrations.RenameField(
            model_name='jobdetails',
            old_name='experience',
            new_name='jobexperience',
        ),
    ]
