# Generated by Django 4.2.2 on 2023-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_experience_candidate_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='companyimage',
            field=models.ImageField(default=False, upload_to='app/img/JobDetails'),
        ),
    ]
